[![CI Pipeline](https://github.com/Raquelsantos242/devcalc-api-tp2/actions/workflows/ci.yml/badge.svg)](https://github.com/Raquelsantos242/devcalc-api-tp2/actions)

# DevCalc API


Gerei um erro proposital com `run: exit 1` e fiz push, recebendo na aba actions a mensagem de erro “Process completed with exit code 1”. Em seguida comentei esse step no workflow, dei push de novo e o erro foi eliminado.

